# Generated by Django 4.2.6 on 2023-10-31 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_phone', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('manager', 'manager'), ('software developer', 'SD'), ('Team Lead', 'TL')], max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
